# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: password

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: password
    salt: "e8L>.HYWPdPg8_=hhd6BF=gE}!p02,Cm1BrHW-RS|euA@v$+VSG|C3^wV+8%,}c."

# Variables to accompany `group_vars/production/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  example.com:
    env:
      db_password: password
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "e8L>.HYWPdPg8_=hhd6BF=gE}!p02,Cm1BrHW-RS|euA@v$+VSG|C3^wV+8%,}c."
secure_auth_key: ">3n8ql^`OIfTHmPf-htZTM>c8lS)G,B:)pPD>PGfaqCxN6}N>B?L{raLy*><JJW+"
logged_in_key: "I4#]?zen;Bk6%2y|_ov)7!nm{QV;4KK@9Xwz7Wy)?Y*@[rVKNzbR4%PGhactG{o@"
nonce_key: "|O$$VOYow6VcK`{Z#2`^zh5`Q(.|%*#u[KWn!i[)xf$a.hGTGayJ13;&b+>z,F=>"
auth_salt: "J7:[5!>pC$.7vmTsx8L:T9ogZ0^19g4a`}8_9P;7A<1PsL$O0iP8;a2Y.f&l2E3G"
secure_auth_salt: "Ddsw=[fI8XcBfC5t#k)2Yvibs_h#--0y5>NE1@(@X*)90m{53iFV`13m_Q!UN;cf"
logged_in_salt: "/Q)n%(u_si6<w/,a:MwboON;:EDR&%(+s-;.MG0Nr-G}&z8WYb34E`L6UZJU4a`e"
nonce_salt: "lRF:XIR3W=2.<^6mBYFFFcL1pc3LSOQXG%FRlPHruO<G{[XS,R[}|z>],*g6^X*a"
